permalink: /posts/:year/:month/:day/:title

encoding: UTF-8

markdown: rdiscount

safe: true

title : Bug.im
author :
  name : Bug.im
  email : xiaoxin11347@gmail.com

production_url : http://bug.im

JB :
  version : 0.3.0

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : bugim

  analytics :
    provider : google
    google :
        tracking_id : 'UA-50024620-1'

  sharing :
    provider : false
